### ISSUE TITLE
403 (Forbidden) error

### ISSUE THREAD

**Issue by rodukov** [Hyper-Dragon/ChessStats#26]
![screenshot](https://github.com/Hyper-Dragon/ChessStats/assets/101352977/35155056-a73d-4294-9d07-98ec76ac37ba)
OS: _Windows 11 22H2_
Username: _dorregard_

The output is an empty file with no information.

**Comment by Hyper-Dragon** [comment]
CDC/Cloudflare has started blocking requests without a user agent string.

FIX: Add user agent string
